export const rootPath = '/';
export const MainPath = '/main'
export const LoginPath = '/login';
export const RegisterPath = '/register';
export const AboutPath = '/about';
export const DetailMonitorPath = '/monitor';
export const DetailDataTanamanPath = '/data-tanaman';
export const DetailCekTanamanPath = '/cek-tanaman';
export const DetailKontakPath = '/kontak';
//export const DetailHcmsPath = '/detail-hidroponik'; //di tambah id nanti
export const DetailSuhuRuangPath = '/suhu-ruang';
export const DetailKelembapanPath = '/kelembapan';
export const DetailKetinggianAirPath = '/ketinggian-air';
export const TanamanHidroponikPath = '/tanaman-hidroponik'
export const SettingPath = '/setting';
export const SeladaPath = '/selada';
export const SawiPath = '/sawi';
export const PakcoyPath = '/pakcoy';
export const TomatPath = '/tomat';

